name: Make release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Build tgz
          run: bash make-release-secure.sh --dirname gh --version ${{ github.ref }}
        - name: Release
          uses: softprops/action-gh-release@v1
          with:
              files: 
                releases/secure-cluster-*.tgz