name: Make release

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Build tgz
          run: bash make-release-secure.sh --dirname gh --version ${{ github.ref }}
          if: startsWith(github.ref, 'refs/tags/')
        - name: Release
          uses: softprops/action-gh-release@v1
          if: startsWith(github.ref, 'refs/tags/')
          with:
              files: 
                secure-cluster-**.tgz